LOCATION_TO_REGION: dict[str, str] = {
    "Arbiters Grounds Entrance Chest": "Arbiters Grounds Entrance",
    "Arbiters Grounds Torch Room East Chest": "Arbiters Grounds Lobby",
    "Arbiters Grounds Torch Room West Chest": "Arbiters Grounds Lobby",
    "Arbiters Grounds Torch Room Poe": "Arbiters Grounds Lobby",
    "Arbiters Grounds East Lower Turnable Redead Chest": "Arbiters Grounds East Wing",
    "Arbiters Grounds East Upper Turnable Chest": "Arbiters Grounds East Wing",
    "Arbiters Grounds East Upper Turnable Redead Chest": "Arbiters Grounds East Wing",
    "Arbiters Grounds Ghoul Rat Room Chest": "Arbiters Grounds East Wing",
    "Arbiters Grounds East Turning Room Poe": "Arbiters Grounds East Wing",
    "Arbiters Grounds Hidden Wall Poe": "Arbiters Grounds East Wing",
    "Arbiters Grounds West Small Chest Behind Block": "Arbiters Grounds West Wing",
    "Arbiters Grounds West Chandelier Chest": "Arbiters Grounds West Wing",
    "Arbiters Grounds West Stalfos West Chest": "Arbiters Grounds West Wing",
    "Arbiters Grounds West Stalfos Northeast Chest": "Arbiters Grounds West Wing",
    "Arbiters Grounds West Poe": "Arbiters Grounds West Wing",
    "Arbiters Grounds Big Key Chest": "Arbiters Grounds After Poe Gate",
    "Arbiters Grounds North Turning Room Chest": "Arbiters Grounds After Poe Gate",
    "Arbiters Grounds Death Sword Chest": "Arbiters Grounds After Poe Gate",
    "Arbiters Grounds Spinner Room First Small Chest": "Arbiters Grounds After Poe Gate",
    "Arbiters Grounds Spinner Room Second Small Chest": "Arbiters Grounds After Poe Gate",
    "Arbiters Grounds Spinner Room Lower Central Small Chest": "Arbiters Grounds After Poe Gate",
    "Arbiters Grounds Spinner Room Stalfos Alcove Chest": "Arbiters Grounds After Poe Gate",
    "Arbiters Grounds Spinner Room Lower North Chest": "Arbiters Grounds After Poe Gate",
    "Arbiters Grounds Stallord Heart Container": "Arbiters Grounds Boss Room",
    "Arbiters Grounds Dungeon Reward": "Arbiters Grounds Boss Room",
    "City in The Sky Argorok Heart Container": "City in The Sky Boss Room",
    "City in The Sky Dungeon Reward": "City in The Sky Boss Room",
    "City in The Sky Central Outside Ledge Chest": "City in The Sky Central Tower Second Floor",
    "City in The Sky Central Outside Poe Island Chest": "City in The Sky Central Tower Second Floor",
    "City in The Sky Big Key Chest": "City in The Sky Central Tower Second Floor",
    "City in The Sky Chest Below Big Key Chest": "City in The Sky Central Tower Second Floor",
    "City in The Sky Poe Above Central Fan": "City in The Sky Central Tower Second Floor",
    "City in The Sky East First Wing Chest After Fans": "City in The Sky East Wing",
    "City in The Sky East Wing Lower Level Chest": "City in The Sky East Wing",
    "City in The Sky East Tile Worm Small Chest": "City in The Sky East Wing",
    "City in The Sky East Wing After Dinalfos Alcove Chest": "City in The Sky East Wing",
    "City in The Sky East Wing After Dinalfos Ledge Chest": "City in The Sky East Wing",
    "City in The Sky Aeralfos Chest": "City in The Sky East Wing",
    "City in The Sky Underwater West Chest": "City in The Sky Entrance",
    "City in The Sky Underwater East Chest": "City in The Sky Entrance",
    # "" : "City in The Sky Lobby",
    "City in The Sky Chest Behind North Fan": "City in The Sky North Wing",
    "City in The Sky West Wing First Chest": "City in The Sky West Wing",
    "City in The Sky West Wing Baba Balcony Chest": "City in The Sky West Wing",
    "City in The Sky West Wing Narrow Ledge Chest": "City in The Sky West Wing",
    "City in The Sky West Wing Tile Worm Chest": "City in The Sky West Wing",
    "City in The Sky Baba Tower Top Small Chest": "City in The Sky West Wing",
    "City in The Sky Baba Tower Narrow Ledge Chest": "City in The Sky West Wing",
    "City in The Sky Baba Tower Alcove Chest": "City in The Sky West Wing",
    "City in The Sky West Garden Corner Chest": "City in The Sky West Wing",
    "City in The Sky West Garden Lone Island Chest": "City in The Sky West Wing",
    "City in The Sky West Garden Lower Chest": "City in The Sky West Wing",
    "City in The Sky West Garden Ledge Chest": "City in The Sky West Wing",
    "City in The Sky Garden Island Poe": "City in The Sky West Wing",
    "Forest Temple Diababa Heart Container": "Forest Temple Boss Room",
    "Forest Temple Dungeon Reward": "Forest Temple Boss Room",
    "Forest Temple Second Monkey Under Bridge Chest": "Forest Temple East Wing",
    "Forest Temple Big Key Chest": "Forest Temple East Wing",
    "Forest Temple East Water Cave Chest": "Forest Temple East Wing",
    "Forest Temple Entrance Vines Chest": "Forest Temple Entrance",
    "Forest Temple Central Chest Behind Stairs": "Forest Temple Lobby",
    "Forest Temple Central North Chest": "Forest Temple Lobby",
    "Forest Temple Central Chest Hanging From Web": "Forest Temple Lobby",
    "Forest Temple Windless Bridge Chest": "Forest Temple North Wing",
    "Forest Temple North Deku Like Chest": "Forest Temple North Wing",
    "Forest Temple East Tile Worm Chest": "Forest Temple North Wing",
    "Forest Temple West Deku Like Chest": "Forest Temple West Wing",
    "Forest Temple Totem Pole Chest": "Forest Temple West Wing",
    "Forest Temple West Tile Worm Room Vines Chest": "Forest Temple West Wing",
    "Forest Temple West Tile Worm Chest Behind Stairs": "Forest Temple West Wing",
    "Forest Temple Big Baba Key": "Forest Temple West Wing",
    "Forest Temple Gale Boomerang": "Ook",
    "Goron Mines Fyrus Heart Container": "Goron Mines Boss Room",
    "Goron Mines Dungeon Reward": "Goron Mines Boss Room",
    "Goron Mines Crystal Switch Room Underwater Chest": "Goron Mines Crystal Switch Room",
    "Goron Mines Crystal Switch Room Small Chest": "Goron Mines Crystal Switch Room",
    "Goron Mines After Crystal Switch Room Magnet Wall Chest": "Goron Mines Crystal Switch Room",
    "Goron Mines Entrance Chest": "Goron Mines Entrance",
    "Goron Mines Magnet Maze Chest": "Goron Mines Lower West Wing",
    "Goron Mines Gor Amato Chest": "Goron Mines Lower West Wing",
    "Goron Mines Gor Amato Small Chest": "Goron Mines Lower West Wing",
    "Goron Mines Gor Amato Key Shard": "Goron Mines Lower West Wing",
    "Goron Mines Main Magnet Room Bottom Chest": "Goron Mines Magnet Room",
    "Goron Mines Main Magnet Room Top Chest": "Goron Mines Magnet Room",
    "Goron Mines Outside Beamos Chest": "Goron Mines North Wing",
    "Goron Mines Outside Underwater Chest": "Goron Mines North Wing",
    "Goron Mines Outside Clawshot Chest": "Goron Mines North Wing",
    "Goron Mines Gor Ebizo Chest": "Goron Mines Upper East Wing",
    "Goron Mines Chest Before Dangoro": "Goron Mines Upper East Wing",
    "Goron Mines Gor Ebizo Key Shard": "Goron Mines Upper East Wing",
    "Goron Mines Dangoro Chest": "Goron Mines Upper East Wing",
    "Goron Mines Beamos Room Chest": "Goron Mines Upper East Wing",
    "Goron Mines Gor Liggs Chest": "Goron Mines Upper East Wing",
    "Goron Mines Gor Liggs Key Shard": "Goron Mines Upper East Wing",
    # "" : "Ganondorf Castle",
    # "" : "Hyrule Castle Entrance",
    "Hyrule Castle Graveyard Grave Switch Room Right Chest": "Hyrule Castle Graveyard",
    "Hyrule Castle Graveyard Grave Switch Room Front Left Chest": "Hyrule Castle Graveyard",
    "Hyrule Castle Graveyard Grave Switch Room Back Left Chest": "Hyrule Castle Graveyard",
    "Hyrule Castle Graveyard Owl Statue Chest": "Hyrule Castle Graveyard",
    # "" : "Hyrule Castle Inside East Wing",
    # "" : "Hyrule Castle Inside West Wing",
    "Hyrule Castle Main Hall Northeast Chest": "Hyrule Castle Main Hall",
    "Hyrule Castle Main Hall Southwest Chest": "Hyrule Castle Main Hall",
    "Hyrule Castle Main Hall Northwest Chest": "Hyrule Castle Main Hall",
    "Hyrule Castle Lantern Staircase Chest": "Hyrule Castle Main Hall",
    "Hyrule Castle East Wing Boomerang Puzzle Chest": "Hyrule Castle Outside East Wing",
    "Hyrule Castle East Wing Balcony Chest": "Hyrule Castle Outside East Wing",
    "Hyrule Castle West Courtyard North Small Chest": "Hyrule Castle Outside West Wing",
    "Hyrule Castle West Courtyard Central Small Chest": "Hyrule Castle Outside West Wing",
    "Hyrule Castle King Bulblin Key": "Hyrule Castle Outside West Wing",
    "Hyrule Castle Southeast Balcony Tower Chest": "Hyrule Castle Third Floor Balcony",
    "Hyrule Castle Big Key Chest": "Hyrule Castle Third Floor Balcony",
    # "" : "Hyrule Castle Tower Climb",
    "Hyrule Castle Treasure Room Eighth Small Chest": "Hyrule Castle Treasure Room",
    "Hyrule Castle Treasure Room Seventh Small Chest": "Hyrule Castle Treasure Room",
    "Hyrule Castle Treasure Room Sixth Small Chest": "Hyrule Castle Treasure Room",
    "Hyrule Castle Treasure Room Fifth Small Chest": "Hyrule Castle Treasure Room",
    "Hyrule Castle Treasure Room Fourth Small Chest": "Hyrule Castle Treasure Room",
    "Hyrule Castle Treasure Room Third Small Chest": "Hyrule Castle Treasure Room",
    "Hyrule Castle Treasure Room Second Small Chest": "Hyrule Castle Treasure Room",
    "Hyrule Castle Treasure Room First Small Chest": "Hyrule Castle Treasure Room",
    "Hyrule Castle Treasure Room Fifth Chest": "Hyrule Castle Treasure Room",
    "Hyrule Castle Treasure Room Fourth Chest": "Hyrule Castle Treasure Room",
    "Hyrule Castle Treasure Room Third Chest": "Hyrule Castle Treasure Room",
    "Hyrule Castle Treasure Room Second Chest": "Hyrule Castle Treasure Room",
    "Hyrule Castle Treasure Room First Chest": "Hyrule Castle Treasure Room",
    "Lakebed Temple Morpheel Heart Container": "Lakebed Temple Boss Room",
    "Lakebed Temple Dungeon Reward": "Lakebed Temple Boss Room",
    "Lakebed Temple Central Room Small Chest": "Lakebed Temple Central Room",
    "Lakebed Temple Central Room Chest": "Lakebed Temple Central Room",
    "Lakebed Temple Chandelier Chest": "Lakebed Temple Central Room",
    "Lakebed Temple Central Room Spire Chest": "Lakebed Temple Central Room",
    "Lakebed Temple East Lower Waterwheel Stalactite Chest": "Lakebed Temple East Wing First Floor",
    "Lakebed Temple East Lower Waterwheel Bridge Chest": "Lakebed Temple East Wing First Floor",
    "Lakebed Temple Before Deku Toad Alcove Chest": "Lakebed Temple East Wing First Floor",
    "Lakebed Temple Before Deku Toad Underwater Left Chest": "Lakebed Temple East Wing First Floor",
    "Lakebed Temple Before Deku Toad Underwater Right Chest": "Lakebed Temple East Wing First Floor",
    "Lakebed Temple Deku Toad Chest": "Lakebed Temple East Wing First Floor",
    "Lakebed Temple East Second Floor Southwest Chest": "Lakebed Temple East Wing Second Floor",
    "Lakebed Temple East Second Floor Southeast Chest": "Lakebed Temple East Wing Second Floor",
    "Lakebed Temple East Water Supply Small Chest": "Lakebed Temple East Wing Second Floor",
    "Lakebed Temple East Water Supply Clawshot Chest": "Lakebed Temple East Wing Second Floor",
    "Lakebed Temple Lobby Left Chest": "Lakebed Temple Entrance",
    "Lakebed Temple Lobby Rear Chest": "Lakebed Temple Entrance",
    "Lakebed Temple Stalactite Room Chest": "Lakebed Temple Entrance",
    "Lakebed Temple West Lower Small Chest": "Lakebed Temple West Wing",
    "Lakebed Temple West Second Floor Central Small Chest": "Lakebed Temple West Wing",
    "Lakebed Temple Underwater Maze Small Chest": "Lakebed Temple West Wing",
    "Lakebed Temple Big Key Chest": "Lakebed Temple West Wing",
    "Lakebed Temple West Second Floor Southwest Underwater Chest": "Lakebed Temple West Wing",
    "Lakebed Temple West Second Floor Northeast Chest": "Lakebed Temple West Wing",
    "Lakebed Temple West Second Floor Southeast Chest": "Lakebed Temple West Wing",
    "Lakebed Temple West Water Supply Small Chest": "Lakebed Temple West Wing",
    "Lakebed Temple West Water Supply Chest": "Lakebed Temple West Wing",
    "Palace of Twilight Collect Both Sols": "Palace of Twilight Entrance",
    "Palace of Twilight West Wing First Room Central Chest": "Palace of Twilight West Wing",
    "Palace of Twilight West Wing Chest Behind Wall of Darkness": "Palace of Twilight West Wing",
    "Palace of Twilight West Wing Second Room Central Chest": "Palace of Twilight West Wing",
    "Palace of Twilight West Wing Second Room Lower South Chest": "Palace of Twilight West Wing",
    "Palace of Twilight West Wing Second Room Southeast Chest": "Palace of Twilight West Wing",
    "Palace of Twilight East Wing First Room North Small Chest": "Palace of Twilight East Wing",
    "Palace of Twilight East Wing First Room Zant Head Chest": "Palace of Twilight East Wing",
    "Palace of Twilight East Wing First Room East Alcove": "Palace of Twilight East Wing",
    "Palace of Twilight East Wing First Room West Alcove": "Palace of Twilight East Wing",
    "Palace of Twilight East Wing Second Room Northeast Chest": "Palace of Twilight East Wing",
    "Palace of Twilight East Wing Second Room Northwest Chest": "Palace of Twilight East Wing",
    "Palace of Twilight East Wing Second Room Southwest Chest": "Palace of Twilight East Wing",
    "Palace of Twilight East Wing Second Room Southeast Chest": "Palace of Twilight East Wing",
    "Palace of Twilight Central First Room Chest": "Palace of Twilight Central First Room",
    "Palace of Twilight Big Key Chest": "Palace of Twilight Outside Room",
    "Palace of Twilight Central Outdoor Chest": "Palace of Twilight Outside Room",
    "Palace of Twilight Central Tower Chest": "Palace of Twilight North Tower",
    "Palace of Twilight Zant Heart Container": "Palace of Twilight Boss Room",
    # "" : "Snowpeak Ruins Left Door",
    # "" : "Snowpeak Ruins Right Door",
    "Snowpeak Ruins Blizzeta Heart Container": "Snowpeak Ruins Boss Room",
    "Snowpeak Ruins Dungeon Reward": "Snowpeak Ruins Boss Room",
    "Snowpeak Ruins Broken Floor Chest": "Snowpeak Ruins Caged Freezard Room",
    "Snowpeak Ruins Chapel Chest": "Snowpeak Ruins Chapel",
    "Snowpeak Ruins Ball and Chain": "Snowpeak Ruins Darkhammer Room",
    "Snowpeak Ruins Chest After Darkhammer": "Snowpeak Ruins Darkhammer Room",
    "Snowpeak Ruins East Courtyard Buried Chest": "Snowpeak Ruins East Courtyard",
    "Snowpeak Ruins East Courtyard Chest": "Snowpeak Ruins East Courtyard",
    "Snowpeak Ruins Lobby Chandelier Chest": "Snowpeak Ruins Entrance",
    "Snowpeak Ruins Lobby West Armor Chest": "Snowpeak Ruins Entrance",
    "Snowpeak Ruins Lobby East Armor Chest": "Snowpeak Ruins Entrance",
    "Snowpeak Ruins Lobby Armor Poe": "Snowpeak Ruins Entrance",
    "Snowpeak Ruins Lobby Poe": "Snowpeak Ruins Entrance",
    "Snowpeak Ruins Ordon Pumpkin Chest": "Snowpeak Ruins Northeast Chilfos Room First Floor",
    "Snowpeak Ruins Northeast Chandelier Chest": "Snowpeak Ruins Northeast Chilfos Room Second Floor",
    "Snowpeak Ruins Ice Room Poe": "Snowpeak Ruins Second Floor Mini Freezard Room",
    "Snowpeak Ruins West Cannon Room Central Chest": "Snowpeak Ruins West Cannon Room",
    "Snowpeak Ruins West Cannon Room Corner Chest": "Snowpeak Ruins West Cannon Room",
    "Snowpeak Ruins West Courtyard Buried Chest": "Snowpeak Ruins West Courtyard",
    "Snowpeak Ruins Courtyard Central Chest": "Snowpeak Ruins West Courtyard",
    "Snowpeak Ruins Wooden Beam Central Chest": "Snowpeak Ruins Wooden Beam Room",
    "Snowpeak Ruins Wooden Beam Northwest Chest": "Snowpeak Ruins Wooden Beam Room",
    "Snowpeak Ruins Wooden Beam Chandelier Chest": "Snowpeak Ruins Wooden Beam Room",
    "Snowpeak Ruins Mansion Map": "Snowpeak Ruins Yeto and Yeta",
    "Temple of Time Armos Antechamber East Chest": "Temple of Time Armos Antechamber",
    "Temple of Time Armos Antechamber North Chest": "Temple of Time Armos Antechamber",
    "Temple of Time Armos Antechamber Statue Chest": "Temple of Time Armos Antechamber",
    "Temple of Time Armogohma Heart Container": "Temple of Time Boss Room",
    "Temple of Time Dungeon Reward": "Temple of Time Boss Room",
    "Temple of Time Poe Behind Gate": "Temple of Time Central Mechanical Platform",
    "Temple of Time First Staircase Gohma Gate Chest": "Temple of Time Connecting Corridors",
    "Temple of Time First Staircase Window Chest": "Temple of Time Connecting Corridors",
    "Temple of Time First Staircase Armos Chest": "Temple of Time Connecting Corridors",
    # "" : "Temple of Time Crumbling Corridor",
    "Temple of Time Darknut Chest": "Temple of Time Darknut Arena",
    "Temple of Time Lobby Lantern Chest": "Temple of Time Entrance",
    "Temple of Time Big Key Chest": "Temple of Time Floor Switch Puzzle Room",
    "Temple of Time Floor Switch Puzzle Room Upper Chest": "Temple of Time Floor Switch Puzzle Room",
    "Temple of Time Moving Wall Beamos Room Chest": "Temple of Time Moving Wall Hallways",
    "Temple of Time Moving Wall Dinalfos Room Chest": "Temple of Time Moving Wall Hallways",
    "Temple of Time Scales Gohma Chest": "Temple of Time Scales of Time",
    "Temple of Time Scales Upper Chest": "Temple of Time Scales of Time",
    "Temple of Time Poe Above Scales": "Temple of Time Scales of Time",
    "Temple of Time Gilloutine Chest": "Temple of Time Upper Spike Trap Corridor",
    "Temple of Time Chest Before Darknut": "Temple of Time Upper Spike Trap Corridor",
    # "" : "Death Mountain Near Kakariko",
    "Death Mountain Alcove Chest": "Death Mountain Trail",
    "Death Mountain Trail Poe": "Death Mountain Trail",
    # "" : "Death Mountain Volcano",
    # "" : "Death Mountain Outside Sumo Hall",
    # "" : "Death Mountain Elevator Lower",
    # "" : "Death Mountain Sumo Hall",
    # "" : "Death Mountain Sumo Hall Elevator",
    # "" : "Death Mountain Sumo Hall Goron Mines Tunnel",
    "Cats Hide and Seek Minigame": "Hidden Village",
    "Ilia Charm": "Hidden Village",
    "Hidden Village Poe": "Hidden Village",
    "Skybook From Impaz": "Hidden Village Impaz House",
    "Kakariko Gorge Owl Statue Chest": "Kakariko Gorge",
    "Kakariko Gorge Double Clawshot Chest": "Kakariko Gorge",
    "Kakariko Gorge Spire Heart Piece": "Kakariko Gorge",
    "Kakariko Gorge Owl Statue Sky Character": "Kakariko Gorge",
    "Kakariko Gorge Male Pill Bug": "Kakariko Gorge",
    "Kakariko Gorge Female Pill Bug": "Kakariko Gorge",
    "Kakariko Gorge Poe": "Kakariko Gorge",
    # "" : "Kakariko Gorge Cave Entrance",
    # "" : "Kakariko Gorge Behind Gate",
    "Eldin Lantern Cave First Chest": "Eldin Lantern Cave",
    "Eldin Lantern Cave Lantern Chest": "Eldin Lantern Cave",
    "Eldin Lantern Cave Second Chest": "Eldin Lantern Cave",
    "Eldin Lantern Cave Poe": "Eldin Lantern Cave",
    # "" : "Kakariko Gorge Keese Grotto",
    "Eldin Field Bomb Rock Chest": "Eldin Field",
    "Bridge of Eldin Owl Statue Chest": "Eldin Field",
    "Goron Springwater Rush": "Eldin Field",
    "Bridge of Eldin Owl Statue Sky Character": "Eldin Field",
    "Eldin Field Male Grasshopper": "Eldin Field",
    "Eldin Field Female Grasshopper": "Eldin Field",
    "Bridge of Eldin Male Phasmid": "Eldin Field",
    "Bridge of Eldin Female Phasmid": "Eldin Field",
    # "" : "Eldin Field Near Castle Town",
    # "" : "Eldin Field Lava Cave Ledge",
    # "" : "Eldin Field From Lava Cave Lower",
    # "" : "North Eldin Field",
    # "" : "Eldin Field Outside Hidden Village",
    # "" : "Eldin Field Grotto Platform",
    "Eldin Stockcave Upper Chest": "Eldin Field Lava Cave Upper",
    "Eldin Stockcave Lantern Chest": "Eldin Field Lava Cave Lower",
    "Eldin Stockcave Lowest Chest": "Eldin Field Lava Cave Lower",
    "Eldin Field Bomskit Grotto Left Chest": "Eldin Field Bomskit Grotto",
    "Eldin Field Bomskit Grotto Lantern Chest": "Eldin Field Bomskit Grotto",
    "Eldin Field Water Bomb Fish Grotto Chest": "Eldin Field Water Bomb Fish Grotto",
    "Eldin Field Stalfos Grotto Right Small Chest": "Eldin Field Stalfos Grotto",
    "Eldin Field Stalfos Grotto Left Small Chest": "Eldin Field Stalfos Grotto",
    "Eldin Field Stalfos Grotto Stalfos Chest": "Eldin Field Stalfos Grotto",
    "Eldin Spring Underwater Chest": "Lower Kakariko Village",
    "Kakariko Village Bomb Rock Spire Heart Piece": "Lower Kakariko Village",
    "Kakariko Village Bomb Shop Poe": "Upper Kakariko Village",
    "Kakariko Village Watchtower Poe": "Upper Kakariko Village",
    "Kakariko Watchtower Alcove Chest": "Upper Kakariko Village",
    "Talo Sharpshooting": "Kakariko Top of Watchtower",
    # "" : "Kakariko Village Behind Gate",
    # "" : "Kakariko Renados Sanctuary Front Left Door",
    # "" : "Kakariko Renados Sanctuary Front Right Door",
    # "" : "Kakariko Renados Sanctuary Back Left Door",
    # "" : "Kakariko Renados Sanctuary Back Right Door",
    "Renados Letter": "Kakariko Renados Sanctuary",
    "Ilia Memory Reward": "Kakariko Renados Sanctuary",
    # "" : "Kakariko Renados Sanctuary Basement",
    "Kakariko Village Malo Mart Hylian Shield": "Kakariko Malo Mart",
    "Kakariko Village Malo Mart Hawkeye": "Kakariko Malo Mart",
    "Kakariko Village Malo Mart Red Potion": "Kakariko Malo Mart",
    "Kakariko Village Malo Mart Wooden Shield": "Kakariko Malo Mart",
    # "" : "Kakariko Elde Inn Left Door",
    # "" : "Kakariko Elde Inn Right Door",
    "Kakariko Inn Chest": "Kakariko Elde Inn",
    # "" : "Kakariko Bug House Door",
    # "" : "Kakariko Bug House Ceiling Hole",
    "Kakariko Village Female Ant": "Kakariko Bug House",
    "Barnes Bomb Bag": "Kakariko Barnes Bomb Shop Lower",
    # "" : "Kakariko Barnes Bomb Shop Upper",
    # "" : "Kakariko Watchtower Lower Door",
    # "" : "Kakariko Watchtower Dig Spot",
    # "" : "Kakariko Watchtower Upper Door",
    "Kakariko Watchtower Chest": "Kakariko Watchtower",
    "Kakariko Graveyard Lantern Chest": "Kakariko Graveyard",
    "Gift From Ralis": "Kakariko Graveyard",
    "Rutelas Blessing": "Kakariko Graveyard",
    "Kakariko Graveyard Male Ant": "Kakariko Graveyard",
    "Kakariko Graveyard Grave Poe": "Kakariko Graveyard",
    "Kakariko Graveyard Open Poe": "Kakariko Graveyard",
    "Kakariko Graveyard Golden Wolf": "Kakariko Graveyard",
    "Coro Bottle": "South Faron Woods",
    # "" : "South Faron Woods Behind Gate",
    # "" : "South Faron Woods Coros Ledge",
    "Faron Woods Owl Statue Sky Character": "South Faron Woods Owl Statue Area",
    # "" : "South Faron Woods Above Owl Statue",
    # "" : "Faron Woods Coros House Lower",
    # "" : "Faron Woods Coros House Upper",
    # "" : "Faron Woods Cave Southern Entrance",
    "South Faron Cave Chest": "Faron Woods Cave",
    # "" : "Mist Area Near Faron Woods Cave",
    "Faron Mist Stump Chest": "Mist Area Inside Mist",
    "Faron Mist North Chest": "Mist Area Inside Mist",
    "Faron Mist South Chest": "Mist Area Inside Mist",
    # "" : "Mist Area Under Owl Statue Chest",
    "Faron Woods Owl Statue Chest": "Mist Area Near Owl Statue Chest",
    "Faron Mist Poe": "Mist Area Center Stump",
    # "" : "Mist Area Outside Faron Mist Cave",
    # "" : "Mist Area Near North Faron Woods",
    # "" : "Faron Woods Cave Northern Entrance",
    "Faron Mist Cave Open Chest": "Mist Area Faron Mist Cave",
    "Faron Mist Cave Lantern Chest": "Mist Area Faron Mist Cave",
    "North Faron Woods Deku Baba Chest": "North Faron Woods",
    "Faron Woods Golden Wolf": "North Faron Woods",
    "Faron Field Bridge Chest": "Faron Field",
    "Faron Field Tree Heart Piece": "Faron Field",
    "Faron Field Male Beetle": "Faron Field",
    "Faron Field Female Beetle": "Faron Field",
    "Faron Field Poe": "Faron Field",
    # "" : "Faron Field Behind Boulder",
    "Faron Field Corner Grotto Right Chest": "Faron Field Corner Grotto",
    "Faron Field Corner Grotto Left Chest": "Faron Field Corner Grotto",
    "Faron Field Corner Grotto Rear Chest": "Faron Field Corner Grotto",
    # "" : "Faron Field Fishing Grotto",
    "Lost Woods Lantern Chest": "Lost Woods",
    "Lost Woods Waterfall Poe": "Lost Woods",
    "Sacred Grove Spinner Chest": "Lost Woods Lower Battle Arena",
    "Lost Woods Boulder Poe": "Lost Woods Lower Battle Arena",
    # "" : "Lost Woods Upper Battle Arena",
    "Sacred Grove Baba Serpent Grotto Chest": "Lost Woods Baba Serpent Grotto",
    # "" : "Sacred Grove Before Block",
    # "" : "Sacred Grove Upper",
    "Sacred Grove Male Snail": "Sacred Grove Lower",
    "Sacred Grove Master Sword Poe": "Sacred Grove Lower",
    "Sacred Grove Pedestal Master Sword": "Sacred Grove Lower",
    "Sacred Grove Pedestal Shadow Crystal": "Sacred Grove Lower",
    "Sacred Grove Past Owl Statue Chest": "Sacred Grove Past",
    "Sacred Grove Female Snail": "Sacred Grove Past",
    "Sacred Grove Temple of Time Owl Statue Poe": "Sacred Grove Past",
    # "" : "Sacred Grove Past Behind Window",
    # "" : "Gerudo Desert Cave of Ordeals Floors 01-11",
    "Cave of Ordeals Floor 17 Poe": "Gerudo Desert Cave of Ordeals Floors 12-21",
    # "" : "Gerudo Desert Cave of Ordeals Floors 22-31",
    "Cave of Ordeals Floor 33 Poe": "Gerudo Desert Cave of Ordeals Floors 32-41",
    "Cave of Ordeals Floor 44 Poe": "Gerudo Desert Cave of Ordeals Floors 42-50",
    "Cave of Ordeals Great Fairy Reward": "Gerudo Desert Cave of Ordeals Floors 42-50",
    "Gerudo Desert Peahat Ledge Chest": "Gerudo Desert",
    "Gerudo Desert East Canyon Chest": "Gerudo Desert",
    "Gerudo Desert Lone Small Chest": "Gerudo Desert",
    "Gerudo Desert West Canyon Chest": "Gerudo Desert",
    "Gerudo Desert South Chest Behind Wooden Gates": "Gerudo Desert",
    "Gerudo Desert Owl Statue Chest": "Gerudo Desert",
    "Gerudo Desert Owl Statue Sky Character": "Gerudo Desert",
    "Gerudo Desert Male Dayfly": "Gerudo Desert",
    "Gerudo Desert Female Dayfly": "Gerudo Desert",
    "Gerudo Desert East Poe": "Gerudo Desert",
    "Gerudo Desert Poe Above Cave of Ordeals": "Gerudo Desert Cave of Ordeals Plateau",
    "Gerudo Desert Northeast Chest Behind Gates": "Gerudo Desert Basin",
    "Gerudo Desert Campfire North Chest": "Gerudo Desert Basin",
    "Gerudo Desert Campfire East Chest": "Gerudo Desert Basin",
    "Gerudo Desert Campfire West Chest": "Gerudo Desert Basin",
    "Gerudo Desert Northwest Chest Behind Gates": "Gerudo Desert Basin",
    "Gerudo Desert North Peahat Poe": "Gerudo Desert North East Ledge",
    "Gerudo Desert North Small Chest Before Bulblin Camp": "Gerudo Desert Outside Bulblin Camp",
    "Outside Bulblin Camp Poe": "Gerudo Desert Outside Bulblin Camp",
    "Gerudo Desert Golden Wolf": "Gerudo Desert Outside Bulblin Camp",
    "Gerudo Desert Skulltula Grotto Chest": "Gerudo Desert Skulltula Grotto",
    # "" : "Gerudo Desert Chu Grotto",
    "Gerudo Desert Rock Grotto Lantern Chest": "Gerudo Desert Rock Grotto",
    "Gerudo Desert Rock Grotto First Poe": "Gerudo Desert Rock Grotto",
    "Gerudo Desert Rock Grotto Second Poe": "Gerudo Desert Rock Grotto",
    "Bulblin Camp First Chest Under Tower At Entrance": "Bulblin Camp",
    "Bulblin Camp Small Chest in Back of Camp": "Bulblin Camp",
    "Bulblin Camp Roasted Boar": "Bulblin Camp",
    "Bulblin Camp Poe": "Bulblin Camp",
    "Bulblin Guard Key": "Bulblin Camp",
    "Outside Arbiters Grounds Lantern Chest": "Outside Arbiters Grounds",
    "Outside Arbiters Grounds Poe": "Outside Arbiters Grounds",
    # "" : "Mirror Chamber Lower",
    # "" : "Mirror Chamber Upper",
    # "" : "Mirror Chamber Portal",
    "Charlo Donation Blessing": "Castle Town West",
    "STAR Prize 1": "Castle Town STAR Game",
    "STAR Prize 2": "Castle Town STAR Game",
    # "" : "Castle Town Center",
    # "" : "Castle Town Goron House Left Door",
    # "" : "Castle Town Goron House Right Door",
    # "" : "Castle Town Goron House",
    "Castle Town Malo Mart Magic Armor": "Castle Town Malo Mart",
    # "" : "Castle Town North",
    "North Castle Town Golden Wolf": "Castle Town North Behind First Door",
    # "" : "Castle Town North Inside Barrier",
    # "" : "Castle Town East",
    "Doctors Office Balcony Chest": "Castle Town Doctors Office Balcony",
    # "" : "Castle Town Doctors Office Left Door",
    # "" : "Castle Town Doctors Office Right Door",
    # "" : "Castle Town Doctors Office Entrance",
    # "" : "Castle Town Doctors Office Lower",
    # "" : "Castle Town Doctors Office Upper",
    # "" : "Castle Town South",
    "Agitha Female Ant Reward": "Castle Town Agithas House",
    "Agitha Female Beetle Reward": "Castle Town Agithas House",
    "Agitha Female Butterfly Reward": "Castle Town Agithas House",
    "Agitha Female Dayfly Reward": "Castle Town Agithas House",
    "Agitha Female Dragonfly Reward": "Castle Town Agithas House",
    "Agitha Female Grasshopper Reward": "Castle Town Agithas House",
    "Agitha Female Ladybug Reward": "Castle Town Agithas House",
    "Agitha Female Mantis Reward": "Castle Town Agithas House",
    "Agitha Female Phasmid Reward": "Castle Town Agithas House",
    "Agitha Female Pill Bug Reward": "Castle Town Agithas House",
    "Agitha Female Snail Reward": "Castle Town Agithas House",
    "Agitha Female Stag Beetle Reward": "Castle Town Agithas House",
    "Agitha Male Ant Reward": "Castle Town Agithas House",
    "Agitha Male Beetle Reward": "Castle Town Agithas House",
    "Agitha Male Butterfly Reward": "Castle Town Agithas House",
    "Agitha Male Dayfly Reward": "Castle Town Agithas House",
    "Agitha Male Dragonfly Reward": "Castle Town Agithas House",
    "Agitha Male Grasshopper Reward": "Castle Town Agithas House",
    "Agitha Male Ladybug Reward": "Castle Town Agithas House",
    "Agitha Male Mantis Reward": "Castle Town Agithas House",
    "Agitha Male Phasmid Reward": "Castle Town Agithas House",
    "Agitha Male Pill Bug Reward": "Castle Town Agithas House",
    "Agitha Male Snail Reward": "Castle Town Agithas House",
    "Agitha Male Stag Beetle Reward": "Castle Town Agithas House",
    # "" : "Castle Town Seer House",
    "Jovani House Poe": "Castle Town Jovanis House",
    "Jovani 20 Poe Soul Reward": "Castle Town Jovanis House",
    "Jovani 60 Poe Soul Reward": "Castle Town Jovanis House",
    "Telma Invoice": "Castle Town Telmas Bar",
    "Lanayru Field Behind Gate Underwater Chest": "Lanayru Field",
    "Lanayru Field Male Stag Beetle": "Lanayru Field",
    "Lanayru Field Female Stag Beetle": "Lanayru Field",
    "Lanayru Field Bridge Poe": "Lanayru Field",
    # "" : "Lanayru Field Cave Entrance",
    # "" : "Lanayru Field Behind Boulder",
    "Lanayru Field Spinner Track Chest": "Hyrule Field Near Spinner Rails",
    "Lanayru Ice Block Puzzle Cave Chest": "Lanayru Ice Puzzle Cave",
    # "" : "Lanayru Field Chu Grotto",
    "Lanayru Field Skulltula Grotto Chest": "Lanayru Field Skulltula Grotto",
    "Lanayru Field Poe Grotto Left Poe": "Lanayru Field Poe Grotto",
    "Lanayru Field Poe Grotto Right Poe": "Lanayru Field Poe Grotto",
    "Hyrule Field Amphitheater Owl Statue Chest": "Outside Castle Town West",
    "Hyrule Field Amphitheater Owl Statue Sky Character": "Outside Castle Town West",
    "West Hyrule Field Male Butterfly": "Outside Castle Town West",
    "West Hyrule Field Female Butterfly": "Outside Castle Town West",
    "Hyrule Field Amphitheater Poe": "Outside Castle Town West",
    "West Hyrule Field Golden Wolf": "Outside Castle Town West",
    # "" : "Outside Castle Town West Grotto Ledge",
    "West Hyrule Field Helmasaur Grotto Chest": "Outside Castle Town West Helmasaur Grotto",
    "East Castle Town Bridge Poe": "Outside Castle Town East",
    "Outside South Castle Town Tightrope Chest": "Outside Castle Town South",
    "Outside South Castle Town Fountain Chest": "Outside Castle Town South",
    "Outside South Castle Town Double Clawshot Chasm Chest": "Outside Castle Town South",
    "Wooden Statue": "Outside Castle Town South",
    "Outside South Castle Town Male Ladybug": "Outside Castle Town South",
    "Outside South Castle Town Female Ladybug": "Outside Castle Town South",
    "Outside South Castle Town Poe": "Outside Castle Town South",
    "Outside South Castle Town Golden Wolf": "Outside Castle Town South",
    # "" : "Outside Castle Town South Inside Boulder",
    "Outside South Castle Town Tektite Grotto Chest": "Outside Castle Town South Tektite Grotto",
    "Lake Hylia Bridge Vines Chest": "Lake Hylia Bridge",
    "Lake Hylia Bridge Owl Statue Chest": "Lake Hylia Bridge",
    "Lake Hylia Bridge Owl Statue Sky Character": "Lake Hylia Bridge",
    "Lake Hylia Bridge Male Mantis": "Lake Hylia Bridge",
    "Lake Hylia Bridge Female Mantis": "Lake Hylia Bridge",
    "Lake Hylia Bridge Cliff Chest": "Lake Hylia Bridge Grotto Ledge",
    "Lake Hylia Bridge Cliff Poe": "Lake Hylia Bridge Grotto Ledge",
    "Lake Hylia Bridge Bubble Grotto Chest": "Lake Hylia Bridge Bubble Grotto",
    "Lake Hylia Underwater Chest": "Lake Hylia",
    "Outside Lanayru Spring Left Statue Chest": "Lake Hylia",
    "Outside Lanayru Spring Right Statue Chest": "Lake Hylia",
    "Flight By Fowl Top Platform Reward": "Lake Hylia",
    "Flight By Fowl Second Platform Chest": "Lake Hylia",
    "Flight By Fowl Third Platform Chest": "Lake Hylia",
    "Flight By Fowl Fourth Platform Chest": "Lake Hylia",
    "Flight By Fowl Fifth Platform Chest": "Lake Hylia",
    "Auru Gift To Fyer": "Lake Hylia",
    "Flight By Fowl Ledge Poe": "Lake Hylia",
    "Isle of Riches Poe": "Lake Hylia",
    "Lake Hylia Alcove Poe": "Lake Hylia",
    "Lake Hylia Dock Poe": "Lake Hylia",
    "Lake Hylia Tower Poe": "Lake Hylia",
    "Plumm Fruit Balloon Minigame": "Lake Hylia",
    # "" : "Lake Hylia Cave Entrance",
    # "" : "Lake Hylia Lakebed Temple Entrance",
    "Lanayru Spring Underwater Left Chest": "Lake Hylia Lanayru Spring",
    "Lanayru Spring Underwater Right Chest": "Lake Hylia Lanayru Spring",
    "Lanayru Spring Back Room Left Chest": "Lake Hylia Lanayru Spring",
    "Lanayru Spring Back Room Right Chest": "Lake Hylia Lanayru Spring",
    "Lanayru Spring Back Room Lantern Chest": "Lake Hylia Lanayru Spring",
    "Lanayru Spring East Double Clawshot Chest": "Lake Hylia Lanayru Spring",
    "Lanayru Spring West Double Clawshot Chest": "Lake Hylia Lanayru Spring",
    "Lake Lantern Cave First Chest": "Lake Hylia Long Cave",
    "Lake Lantern Cave Second Chest": "Lake Hylia Long Cave",
    "Lake Lantern Cave Third Chest": "Lake Hylia Long Cave",
    "Lake Lantern Cave Fourth Chest": "Lake Hylia Long Cave",
    "Lake Lantern Cave Fifth Chest": "Lake Hylia Long Cave",
    "Lake Lantern Cave Sixth Chest": "Lake Hylia Long Cave",
    "Lake Lantern Cave Seventh Chest": "Lake Hylia Long Cave",
    "Lake Lantern Cave Eighth Chest": "Lake Hylia Long Cave",
    "Lake Lantern Cave Ninth Chest": "Lake Hylia Long Cave",
    "Lake Lantern Cave Tenth Chest": "Lake Hylia Long Cave",
    "Lake Lantern Cave Eleventh Chest": "Lake Hylia Long Cave",
    "Lake Lantern Cave Twelfth Chest": "Lake Hylia Long Cave",
    "Lake Lantern Cave Thirteenth Chest": "Lake Hylia Long Cave",
    "Lake Lantern Cave Fourteenth Chest": "Lake Hylia Long Cave",
    "Lake Lantern Cave End Lantern Chest": "Lake Hylia Long Cave",
    "Lake Lantern Cave First Poe": "Lake Hylia Long Cave",
    "Lake Lantern Cave Second Poe": "Lake Hylia Long Cave",
    "Lake Lantern Cave Final Poe": "Lake Hylia Long Cave",
    "Lake Hylia Shell Blade Grotto Chest": "Lake Hylia Shell Blade Grotto",
    "Lake Hylia Water Toadpoli Grotto Chest": "Lake Hylia Water Toadpoli Grotto",
    "Upper Zoras River Female Dragonfly": "Upper Zoras River",
    "Upper Zoras River Poe": "Upper Zoras River",
    "Iza Helping Hand": "Upper Zoras River Izas House",
    "Iza Raging Rapids Minigame": "Upper Zoras River Izas House",
    "Fishing Hole Heart Piece": "Fishing Hole",
    "Fishing Hole Bottle": "Fishing Hole",
    # "" : "Fishing Hole House",
    "Zoras Domain Chest By Mother and Child Isles": "Zoras Domain",
    "Zoras Domain Chest Behind Waterfall": "Zoras Domain",
    "Zoras Domain Male Dragonfly": "Zoras Domain",
    "Zoras Domain Mother and Child Isle Poe": "Zoras Domain",
    "Zoras Domain Waterfall Poe": "Zoras Domain",
    # "" : "Zoras Domain West Ledge",
    "Zoras Domain Light All Torches Chest": "Zoras Throne Room",
    "Zoras Domain Extinguish All Torches Chest": "Zoras Throne Room",
    "Zoras Domain Underwater Goron": "Zoras Throne Room",
    # "" : "Outside Links House",
    "Wooden Sword Chest": "Ordon Links House",
    "Links Basement Chest": "Ordon Links House",
    "Uli Cradle Delivery": "Ordon Village",
    "Ordon Cat Rescue": "Ordon Seras Shop",
    "Sera Shop Slingshot": "Ordon Seras Shop",
    "Ordon Shield": "Ordon Shield House",
    "Ordon Sword": "Ordon Sword House",
    # "" : "Ordon Bos House Left Door",
    # "" : "Ordon Bos House Right Door",
    "Wrestling With Bo": "Ordon Bos House",
    # "" : "Ordon Ranch Entrance",
    "Herding Goats Reward": "Ordon Ranch",
    # "" : "Ordon Ranch Stable",
    "Ordon Ranch Grotto Lantern Chest": "Ordon Ranch Grotto",
    "Ordon Spring Golden Wolf": "Ordon Spring",
    "Ashei Sketch": "Snowpeak Climb Lower",
    "Snowpeak Above Freezard Grotto Poe": "Snowpeak Climb Upper",
    "Snowpeak Blizzard Poe": "Snowpeak Climb Upper",
    "Snowpeak Poe Among Trees": "Snowpeak Climb Upper",
    # "" : "Snowpeak Ice Keese Grotto",
    "Snowpeak Freezard Grotto Chest": "Snowpeak Freezard Grotto",
    "Snowpeak Cave Ice Lantern Chest": "Snowpeak Summit Upper",
    "Snowboard Racing Prize": "Snowpeak Summit Upper",
    "Snowpeak Cave Ice Poe": "Snowpeak Summit Upper",
    "Snowpeak Icy Summit Poe": "Snowpeak Summit Lower",
}
